parameters:
- name: 'ProyectName'
  type: string
  default: ''



stages: 
- stage: CI
  displayName: Build
  variables:
    - group: ConnectDb
    - name: tag
      value: '0.0.$(Build.BuildId)'
  pool: Default
  jobs:
  - job: 
    displayName: Build  
    steps:
    - task: replacetokens@5
      inputs:
        rootDirectory: $(Build.SourcesDirectory)
        targetFiles: '**/*.properties'
        encoding: 'auto'
        tokenPattern: 'rm'
        writeBOM: true
        actionOnMissing: 'warn'
        keepToken: false
        actionOnNoFiles: 'continue'
        enableTransforms: false
        enableRecursion: false
        useLegacyPattern: false
        enableTelemetry: true

    - bash: |
        cd $(Build.SourcesDirectory)
        chmod +x gradlew
        ./gradlew bootJar
      displayName: Build project
  
  - job:
    displayName: Test
    steps:
      - checkout: none
      - bash: |
          cd $(Build.SourcesDirectory)
          ls

  - job:
    displayName: Package
    steps:
      - checkout: none
      - task: Docker@2
        displayName: Build and Push Docker image
        inputs:
          containerRegistry: 'MyConnect'
          repository: 'camilolagos/cliente-service'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: '$(tag)'
    

